name: Publish to Maven Central

on:
  release:
    types: [published] # Trigger on a new GitHub Release being published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for actions/checkout
      packages: write # If you also plan to publish to GitHub Packages, otherwise can be removed
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # Or 'zulu', 'adopt', etc.
        java-version: '21'
        # Configure Maven settings for Sonatype authentication
        server-id: sonatype-nexus-staging # Matches the ID in your pom.xml distributionManagement
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        # Configure GPG for artifact signing
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Build and Publish to Maven Central
      run: mvn clean antlr4:antlr4 deploy -Prelease -DskipTests
      # -Prelease activates the release profile if you have one.
      # -DskipTests skips tests during deployment, often desired for releases.
      env:
        # Pass secrets as environment variables, which setup-java uses to create settings.xml
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
